// <auto-generated />
namespace StoreComplete.WebMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ititial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ititial));
        
        string IMigrationMetadata.Id
        {
            get { return "201808081646524_ititial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
